### ISSUE TITLE
Why the {.validate, property.} pragmas?

### ISSUE THREAD

**Issue by brimbur** [khchen/wNim#1]
In examples\wHyperlink.nim, why not just have:

```
  wHyperLink* = ref object of wStaticText
    url: string
    markedColor: wColor
    visitedColor: wColor
    normalColor: wColor
    hoverFont: wFont
    normalFont: wFont
    isMouseHover: bool
    isPressed: bool
    isVisited: bool

proc `hoverFont=`*(self: wHyperLink not nil, font: wFont) =
  self.hoverFont = font
  if self.isMouseHover:
    self.wWindow.setFont(self.hoverFont)
    self.fit()

```

**Comment by khchen** [comment]
1. The function names in wNim are most identical to wxWidgets, and some setter have more than one parameters. So you can use wxWidgets style, or use Nim style if the setter only have one parameter. Adding property let you have a chance to select coding style.

2. In my test, not nil not yet works very well even in devel version. It cannot always insure "not nil" in all case. So I add validate macro.
