### ISSUE TITLE
Disable/Enable Controls

### ISSUE THREAD

**Issue by super-tomcat** [khchen/wNim#101]
Not sure if ive missed this setting somewhere, but is there any way to disable/enable a control?

**Comment by bunkford** [comment]
You can use from wWindow:

```Nim
myControl.disable()
myControl.enable()
```

**Comment by super-tomcat** [comment]
> 
> 
> You can use from wWindow:
> 
> ```nim
> myControl.disable()
> myControl.enable()
> ```

Lovely Jubbly

thanks
