### ISSUE TITLE
wTextCtrl - Background Colors

### ISSUE THREAD

**Issue by super-tomcat** [khchen/wNim#103]
Is it possible to set different background colors for each character in a wTextCtrl?

**Comment by khchen** [comment]
Yes, you need wTeR. Example:
https://github.com/khchen/wNim/blob/master/examples/textctrl.nim

screenshot:
![Snipaste](https://user-images.githubusercontent.com/5612339/196061532-08c4d767-7de8-46bf-95dd-77e952660e39.png)
