### ISSUE TITLE
[Help] wFileDialog returns an empty sequence when using wFdMultiple.

### ISSUE THREAD

**Issue by Aetopia** [khchen/wNim#111]
```nim
import wNim/wFileDialog
var fd = FileDialog(style=wFdOpen or wFdMultiple or wFdFileMustExist)
echo fd.display()
```
Using this code snippet simply returns an empy sequence when selecting multiple files.

I am not sure if this some issue with wNim or the parameters, I have passed to the `FileDialog` function.

**Comment by khchen** [comment]
Thanks for report. After testing, this is a regression bug of strutils since nim 1.6.0. Nim 1.4.7 works correctly.
This code leads the problem:

```nim
import strutils
echo "abc\0\0\0".find("\0\0")
```

Nim 1.4.3 output 3.
Nim 1.6.0 output 0.

**Comment by Aetopia** [comment]
Oh, thank you!

**Comment by khchen** [comment]
Bug is in strutils. wNim won't be fixed.
