### ISSUE TITLE
Compiler fails on last devel 0.19.9 (after 2018-2-26)

### ISSUE THREAD

**Issue by zolern** [khchen/wNim#12]
wNim\private'wWindow, line 746

`SetLayeredWindowAttributes(self.mHwnd, 0, alpha, LWA_ALPHA)`

**alpha** is declared as range[0..255], but SetLayeredWindowAttributes expects BYTE
Simple **BYTE(alpha)** resolves compiler errors

BTW: several deprecated warnings are shown about initSet -> initHashSet in wApp, wResizer and wMenuBar

**Comment by khchen** [comment]
Thanks for your report.
I will fix this problem in next major release.

Current devel version (0.19.9) have a terrible bug about union in object.
This bug breaks all object (struct in c) contains union in winim.
Next release will be uploaded after this bug fixed.

**Comment by khchen** [comment]
fixed
