### ISSUE TITLE
Demo is broken when built with -d:release

### ISSUE THREAD

**Issue by avionbg** [khchen/wNim#13]
Building the demo with -d:release breaks the exe, when launched it reports: 
`SIGSEGV: Illegal storage access. (Attempt to read from nil?)`
During compile time this `error?` is printed : Hint:  [Link]
G:/DEV/C-C++/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .rsrc merge failure: multiple non-default manifests
Hint: operation successful (142161 lines compiled; 13.099 sec total; 275.813MiB peakmem; Release Build) [SuccessX]

**Comment by khchen** [comment]
I already this bug. It will be fixed in next release.
However, still thanks for your report.

**Comment by khchen** [comment]
fixed
