### ISSUE TITLE
demo.nim crashes for latest nim

### ISSUE THREAD

**Issue by retsyo** [khchen/wNim#19]
The details are reported as https://github.com/nim-lang/Nim/issues/11093#issuecomment-485853543

**Comment by khchen** [comment]
This is still a compiler's bug, not wNim's bug. 
I already report it.  https://github.com/nim-lang/Nim/issues/11489
For now, I don't know how overcome it. 
The only way is waiting the newer compiler...

**Comment by khchen** [comment]
A hotfix was added for this bug.
