### ISSUE TITLE
Compiler error: ambiguous call of `$`, nim 0.20

### ISSUE THREAD

**Issue by zolern** [khchen/wNim#21]
Compiler can't determine what $ to use: system's or winstr's

**- wNim/private/controls/wHyperlinkCtrl.nim**: [line 103](https://github.com/khchen/wNim/blob/master/wNim/private/controls/wHyperlinkCtrl.nim#L103) and [line 109](https://github.com/khchen/wNim/blob/master/wNim/private/controls/wHyperlinkCtrl.nim#L109)

**- wNim/private/events/wHyperLinkEvent.nim**: [line 37](https://github.com/khchen/wNim/blob/master/wNim/private/events/wHyperLinkEvent.nim#L37) and [line 42](https://github.com/khchen/wNim/blob/master/wNim/private/events/wHyperLinkEvent.nim#L42)

**- wNim/private/gdiobjects/wFont.nim**: [line 135](https://github.com/khchen/wNim/blob/master/wNim/private/gdiobjects/wFont.nim#L135)

The easiest fix is to replace **$** with **winstr.\`$\`**

**Comment by khchen** [comment]
Fixed.
