### ISSUE TITLE
How to display scrollbar of TextCtrl?

### ISSUE THREAD

**Issue by nnahito** [khchen/wNim#26]
I'm a Japanese.
And I'm not good at English.
So my English is maybe bad.
Sorry.

---

I want to display scrollbar in TextCtrl appended wTeMultiLine.
I input texts in TextCtrl  overflowing.
However, it didn't display the vertical scrollbar.

In [documents](https://khchen.github.io/wNim/wTextCtrl.html), they are not written how to display vertical scrollbar in TextCtrl.
(But it is written how to display horizontal scrollbar.)

Please teach me how to display the vertical scrollbar in TextCtrl.

**Comment by Guevara-chan** [comment]
`style=wVScroll`

**Comment by khchen** [comment]
You can try to add wVScroll and wHScroll, etc. These are wWindow's styles, but of course they can be used in it's subclasses. Here is the [document](https://khchen.github.io/wNim/wWindow.html).
