### ISSUE TITLE
Change the style of Text Control after its displayed?

### ISSUE THREAD

**Issue by super-tomcat** [khchen/wNim#30]
I am trying to change the wTeDontWrap style of a Text Control after it is shown... specifically I want to be able to turn Wrap On for a control that initially has it turned Off... but I cannot see how to change the style after the control has been displayed.
Ive tried:

 myTextControl.clearWindowStyle(wTeDontWrap)

but it did not work.

**Comment by khchen** [comment]
https://docs.microsoft.com/en-us/windows/win32/controls/edit-control-styles
> After the control has been created, these styles cannot be modified, except as noted.

The only way is to delete and then recreate the control. For example:
```nim
import wNim

let app = App()
let frame = Frame(title="TextCtrl", size=(350, 200))
let panel = Panel(frame)
let button = Button(panel, label="Change")

var textctrl = TextCtrl(panel, style=wTeMultiLine or wTeDontWrap)
textctrl.value = "The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog."

proc layout() =
  panel.autorelayout """
    H:|[textctrl,button]|
    V:|[textctrl],[button(30)]|
  """

button.wEvent_Button do ():
  let newStyle = textctrl.windowStyle xor wTeDontWrap
  let newValue = textctrl.value
  textctrl.delete()
  textctrl = TextCtrl(panel, style=newStyle, value=newValue)
  layout()

panel.wEvent_Size do ():
  layout()

layout()
frame.center()
frame.show()
app.mainLoop()
```
