### ISSUE TITLE
-1 can't be converted to DWORD_PTR

### ISSUE THREAD

**Issue by retsyo** [khchen/wNim#36]
I  am using latest cloned-and-built nim on win 7 64 bits. Lasted wNim is installed via `nim install wnim`

```bash
$ nim c -r demo.nim
...
C:\Users\USER\.nimble\pkgs\wnim-0.8.0\wNim\private\controls\wToolBar.nim(336, 36) Error: -1 can't be converted to DWORD_PTR

```

**Comment by khchen** [comment]
I know this problem and the same problem in winim is already fixed.
wNim will be fixed in next release. Thanks.

**Comment by khchen** [comment]
Fixed.
