### ISSUE TITLE
DPI aware issue

### ISSUE THREAD

**Issue by drthinh** [khchen/wNim#37]
Applications appear blur and unclarity when display in Full HD display

**Comment by khchen** [comment]
Does wSetSysemDpiAware() or wSetPerMonitorDpiAware() work or not?

**Comment by drthinh** [comment]
Thanks for your reply,
I have researched document, but didn't find DPI aware functions, only: getDpi, getDpiScaleRatio, dpiScale. I think it is a common problem, should it be noticed in document.
btw, after add "wSetSysemDpiAware()", it is nice now! Thank you :D

**Comment by khchen** [comment]
Because this function is not belong to a window. 
The document: https://khchen.github.io/wNim/wUtils.html
