### ISSUE TITLE
Can i inherit from wForm ?

### ISSUE THREAD

**Issue by vinodvinu** [khchen/wNim#40]
Hi,
Can i inherit from wForm ?
Now, FormClass = ref object of wFrame is not working. Please show me some examples.

**Comment by Guevara-chan** [comment]
Actually... https://github.com/khchen/wNim/blob/master/examples/subclassing.nim - no ?

**Comment by khchen** [comment]
> Actually... https://github.com/khchen/wNim/blob/master/examples/subclassing.nim - no ?

You get it.
