### ISSUE TITLE
Examples with images are not being cross-compiled from Mac (?)

### ISSUE THREAD

**Issue by pateketrueke** [khchen/wNim#41]
Hi, awesome project!

I'm using a Mac to cross-compile the examples, and everything's perfect. 😍 

Only images are not being resolved as-is, because they're using  `images\1.png` and nim compiler is not able to found them, once I change the directory separator to `/` then they compiled without issues. 🍻 

Not sure if this is an issue, or if there's a cross-way to handle those paths, what do you think?

**Comment by khchen** [comment]
I will consider to use ```/``` instead of ```\``` in the future. Or to use https://nim-lang.org/docs/os.html#%2F%2Cstring%2Cstring instead.

**Comment by khchen** [comment]
Fixed.
