### ISSUE TITLE
Help cannot compile reversi.nim

### ISSUE THREAD

**Issue by Lecale** [khchen/wNim#42]
Hi I download with github and use this to compile file 
`nim c -d:release --opt:size --passL:-s --app:gui reversi.nim`
but I see an error I do not understand
```
C:/Users/sivad/.choosenim/toolchains/mingw32/bin/../lib/gcc/i686-w64-mingw32/4.9.1/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lgdi32
C:/Users/sivad/.choosenim/toolchains/mingw32/bin/../lib/gcc/i686-w64-mingw32/4.9.1/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lcomdlg32
Error: execution of an external program failed: 'gcc.exe  @reversi_linkerArgs.txt'
```
Do you know what I did wrong?
Thank you.

**Comment by khchen** [comment]
Which version of mingw do you use?
However, this seems not the problem of wNim, IMO.
