### ISSUE TITLE
Can not set ListBox as drop target

### ISSUE THREAD

**Issue by janicetr** [khchen/wNim#43]
Hey!

If I create a ListBox and set it as drop target

> let listbox = ListBox(panel, style = wLbSingle or wLbNeededScroll)
> listbox.setDropTarget()

when I drag a file over it, the mouse cursor changes to stop sign and I am unable to drop the file.

Win10 x64, Nim 1.0.4, wNim 0.10.1

Can you help me with this one, please?

**Comment by khchen** [comment]
You also have to handle wEvent_DragEnter, wEvent_DragOver, wEvent_Drop, etc.
See dragdrop.nim for example.
