### ISSUE TITLE
how to put text with ENTER in textcontrol

### ISSUE THREAD

**Issue by retsyo** [khchen/wNim#46]
the following code only puts "helloworld" in the textcontrol, however it is supposed to be
```
hello
world
```
so how to fix it? Thanks

```python
import wNim

let app = App()
let frame = Frame()
let panel = Panel(frame)

let textctrl = TextCtrl(panel,
    value="hello\nworld",
    style=wBorderSunken or wTeMultiLine or wTeReadOnly,
)

proc layout() =
    panel.autolayout """
        HV: |[textctrl]|
    """

panel.wEvent_Size do ():
  layout()

layout()
frame.center()
frame.show()
app.mainLoop()

```

**Comment by khchen** [comment]
Use "\r\n" in Windows system instead of "\n".

**Comment by retsyo** [comment]
I think I wrote a bad code above, which should be 
```python
value = """hello
world"""
```
i.e. long string literals is used. In this case, could it be better if wNim treats '\n' as '\r\n' automatically?

**Comment by khchen** [comment]
I don't think "automatically" by wNim is a good idea. However, you can do the conversion by yourself on compile time. For example:
```nim
import winim/lean, strutils

const value = """hello
world""".replace("\n", "\r\n")

echo value.repr
```
