### ISSUE TITLE
tutorial request: get event object, batch bindng

### ISSUE THREAD

**Issue by retsyo** [khchen/wNim#5]
the example shows that
```nim
btn1.wEvent_MouseEnter do ():
    statusBar.setStatusText("in")

btn1.wEvent_MouseLeave do ():
    statusBar.setStatusText("out")
```

now I have many controls (btn1, btn2, txt1, txt2, and so on), I think it is better to give detailed instruction/help. But I did not know how to 
1. bind all controls' wEvent_MouseLeave to clear statusBar. Is there any batch way, for example
```nim
for i in (btn1, btn2):
    i.wEvent_MouseLeave do ():
        statusBar.setStatusText("")
```

2. get the current control class(Button, TextCtrl...)

3. get the current control, so that we can do something like
```nim
proc onMouseIn(evt):
    if evt.control.id = "mysave":
        do some save
    elif:
        do else
```

thanks

**Comment by khchen** [comment]
Maybe you need **closureScope**, I think you already got it.
https://github.com/retsyo/nim-myMsgBox
