### ISSUE TITLE
How to inject something in app.mainLoop()

### ISSUE THREAD

**Issue by Dev1lroot** [khchen/wNim#50]
for eg. I have an echo "test"
can I insert it in app.mainLoop() to echo test while loop is running?

**Comment by khchen** [comment]
For current version, you cannot do that. 
To achieve this function, I must design a callback or something like in following version.
However, is it really necessary?

**Comment by Dev1lroot** [comment]
really necessary, of course!

**Comment by khchen** [comment]
Added.
