### ISSUE TITLE
How to set the frame position according to the screen size

### ISSUE THREAD

**Issue by EasiestSoft** [khchen/wNim#52]
How to set the frame position according to the screen size

It seems that I can only center the frame, but sometimes I don’t want to center the frame, but set x to (screen.width - frame.width -100) and y to (screen.height - frame.height -100) , how can I do that

**Comment by khchen** [comment]
Of course you can. For example:
```nim
import wNim/[wApp, wFrame, wUtils]

var app = App()
var frame = Frame()

let screen = wGetScreenSize()

frame.position = (screen.width - frame.size.width - 100,
  screen.height - frame.size.height - 100)

frame.show()
app.mainLoop()
```

**Comment by EasiestSoft** [comment]
Thanks
I love Nim and I love wNim
