### ISSUE TITLE
How to set transparency

### ISSUE THREAD

**Issue by BugFix** [khchen/wNim#55]
I want to have an statictext on a bitmap, but transparent. How can I do this?
I've tried:

`let staticbitmap = StaticBitmap(panel, bitmap=Bitmap(myImage))`
`let staticText = StaticText(staticbitmap, label="Hello, World!", style=wTransparentWindow) # doesn't work`
`# create staticText with default style and sets the transparency fails too:`
`staticText.setTransparent(120)`

Any ideas?

**Comment by khchen** [comment]
You can deal with wEvent_Paint event and try to paint what you want. For example:
```nim
import wNim/[wApp, wFrame, wPanel, wBitmap, wPaintDC, wFont]

var
  app = App()
  frame = Frame(title = "Demo")
  panel = Panel(frame)
  bitmap = Bitmap(r"release\examples\images\logo.png")

panel.wEvent_Paint do ():
  var
    dc = PaintDC(panel)
    rect = (0, 0, bitmap.size.width, bitmap.size.height)

  dc.backgroundTransparent = true
  dc.font = Font(18)
  dc.drawBitmap(bitmap)
  dc.drawLabel("Hello, World", rect, wRight or wBottom)

frame.center()
frame.show()
app.mainLoop()
```

**Comment by BugFix** [comment]
Thank you. That helps a lot.
btw: I love wNim, an impressive work.
