### ISSUE TITLE
--gc:arc fails on tictactoe.nim example

### ISSUE THREAD

**Issue by mathysr** [khchen/wNim#57]
Compiling the tictactoe.nim example with --gc:arc fails. Giving following error:

Error: cannot bind another '=destroy' to: FlowVarObj; previous declaration was constructed here implicitly: 
... \.nimble\pkgs\wnim-0.11.1\wNim\private\wMacros.nim(128, 18)

I see no final method in tictactoe.nim, but then it gets in trouble somewhere the wMacros.nim module, even when adding a final method to the tictactoe.nim file.

Nim version 1.2.4 on Windows AMD64
wNim@0.11.1

**Comment by khchen** [comment]
I am sure that this is bug of nim compiler, not bug of wNim.
