### ISSUE TITLE
wNim/wImageList - Icon selection by index fails

### ISSUE THREAD

**Issue by BugFix** [khchen/wNim#64]
Hello Ward,
there is a problem with the procedures **getBitmap** and **getIcon** from wNim/wImageList.
Both procedures use the parameter **index** to identify the icon. Actually the index should be passed to the calls of ImageList_GetImageInfo or ImageList_GetIcon. But in both cases **0** is passed statically. So the first icon is always chosen.

getBitmap:
```Nim
ImageList_GetImageInfo(self.mHandle, 0, &info)
```
getIcon:
```Nim
ImageList_GetIcon(self.mHandle, 0, ILD_TRANSPARENT)
```

The problem can be solved if 
```Nim
cast[int32](index)
```
is passed instead of **0**.

**Comment by khchen** [comment]
Fixed.
