### ISSUE TITLE
Paint clone example

### ISSUE THREAD

**Issue by rocket111185** [khchen/wNim#66]
Hi, Ward!
I'm new to Nim, so I wanted to try to make something for training.

But I can't even start, because I don't understand, how to make a drawable part.
Can you make a simple example, just a window (wFrame) with a drawable part and one instrument (pen)?

**Comment by khchen** [comment]
He is the example.

https://github.com/khchen/wNim/blob/master/examples/scribble.nim

**Comment by rocket111185** [comment]
Thank you so much. You're a man of culture)
