### ISSUE TITLE
Grid control for wNim libaray

### ISSUE THREAD

**Issue by leeooox** [khchen/wNim#68]
Hello Khchen,

Does the wNim have grid control(similar to wx.grid) as spreadsheet?  I am considering use wNim as GUI for a new project as the code is compact and the executable size is very small, but the grid is mandatory to me....
This is a not an issue, but a question, thanks.

Aaron

**Comment by khchen** [comment]
wNim don't have grid control by itself. 
However, you can consider use grid control DLL as plugin. 
For example, https://github.com/bunkford/wZeeGrid
Or you can wrap grid control in http://www.mctrl.org/ .

**Comment by leeooox** [comment]
@khchen , thanks for the information. This is one more support for me to choose nim and wNim.
