### ISSUE TITLE
About autolayout and dpi scale

### ISSUE THREAD

**Issue by codehz** [khchen/wNim#70]
How to scale the hardcoded numbers in autolayout dsl?

**Comment by codehz** [comment]
possible solution:
```nim
import wnim/[wWindow, wApp, autolayout]
import macros

macro scaled_autolayout*(parent: wResizable, input: static[string]): untyped =
  var parser = initVflParser(parent.repr)
  parser.parse(input)
  let nested = parseStmt(parser.toString(templ="layout"))
  result = quote do:
    `parent`.dpiAutoScale(`nested`)
```

**Comment by khchen** [comment]
Your workaround is really good. However, it will encounter problem for some case, for example:
```
      H:|-[view(50%)]
      V:|-[view(50%)]
```

To resolve the problem, I want to introduce the **quoted with backticks** syntax for autolayout.
The code may look like:
```nim
panel.dpiAutoScale:
  let
    bar = 10
    w = 90
    h = 30

panel.autolayout """
  H: |-`bar`-[button(`w`)]
  V: |-`bar`-[button(`h`)]
"""
```

**Comment by codehz** [comment]
> However, it will encounter problem for some case

It wont
https://github.com/khchen/wNim/blob/06d47ca22a8be81173184ccc677056fc272b901c/wNim/private/autolayout.nim#L277
the 100 will also get scaled (Although it may cause small errors in the process of converting between integers and floating point numbers)

But it must be admitted that this is a hacky solution...

## Another solution

Maybe we can just introduce a distinct number type, that implemented width, height, innerWidth, innerHeight

```nim
type DpiValue* = distinct int
proc width*(v: DpiValue): int = v.int
proc height*(v: DpiValue): int = v.int
# skip others

panel.dpiAutoScale:
  let
    bar = 10.DpiValue
    w = 90.DpiValue
    h = 30.DpiValue

panel.autolayout """
  H: |-bar-[button(w)]
  V: |-bar-[button(h)]
"""
will compile to
```nim
panel.layout:
  button:
    left = panel.left + bar.width
    width = w.width
    top = panel.top + bar.height
    height = h.height
```

**Comment by khchen** [comment]
Cool idea. However, quoted syntax are more flexible. For example, allow to embed some procs:
```nim
panel.dpiAutoScale:
  proc bar(): int = 10
  proc getWidth(): int = 90
  proc getHeight(): int = 30

panel.autolayout """
  H: |-`bar()`-[button(`getWidth()`)]
  V: |-`bar()`-[button(`getHeight()`)]
"""
```

**Comment by khchen** [comment]
The quote syntax is added in the last version of autolayout.
