### ISSUE TITLE
no underscored line in menu item

### ISSUE THREAD

**Issue by retsyo** [khchen/wNim#73]
I am using latest wnim and winim on mingw64+msys2. For your `examples\menu.nim`, there is `"&File"` for menu, so there should be underscored line under `F`. However, there is no such underscored line in menus and menu items.

**Comment by khchen** [comment]
Is this a bug of wNim?

**Comment by retsyo** [comment]
yes, I think it is a bug

**Comment by khchen** [comment]
What bug for wNim will appear only in mingw64+msys2 ?

**Comment by retsyo** [comment]
Aha, it seems that the underscored lines only show when we pressed `Alt` on Windows 10. So it is not a bug, no matter in wNim or Windows 10. Maybe it is a feature of Windows 10.
Sorry and closed.
