### ISSUE TITLE
Help needed: How to get the position of a scroll bar in ListCtrl?

### ISSUE THREAD

**Issue by nnahito** [khchen/wNim#85]
I want to create a mechanism in ListCtrl that will automatically scroll to the bottom when an item is added, but only when the scrollbar is at the bottom.

However, there doesn't seem to be a method in the help to get the position of the scrollbar.
https://khchen.github.io/wNim/wListCtrl.html

Is it possible to get the position of the scroll bars and achieve what I want?

I would appreciate it if you could let me know.
Thank you very much.

**Comment by khchen** [comment]
You should try [proc ensureVisible()](https://khchen.github.io/wNim/wListCtrl.html#ensureVisible%2CwListCtrl%2Cint).

**Comment by nnahito** [comment]
Thank you for your reply.
I'll try it.
Thank you!
