### ISSUE TITLE
error: lvalue required as unary '&' operand

### ISSUE THREAD

**Issue by mbenam** [khchen/wNim#86]
Hello,

I am trying out the examples. In every case I am getting the following error multiple times throughout the compilation. After searching, it seems to be an issue related to the c++ file generated. Thank you.

C:\Users\menam\nimcache\printpreview_d\@m..@s..@s..@s.nimble@spkgs@swnim-0.11.2@swNim@sprivate@swHelper.nim.c:1624:11: error: lvalue required as unary '&' operand
    T18_ = &((&bitmapInfo));
           ^

**Comment by khchen** [comment]
Cannot reproduce.
What is your environment?

**Comment by khchen** [comment]
Fixed in winim.
